import "@/app/_styles/globals.css";
import NextTopLoader from "nextjs-toploader";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { Josefin_Sans, Nunito } from "next/font/google";
import { SupportProvider } from "@/app/_context/SupportContext";
import { AuthProvider } from "./_context/AuthContext";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});
const nunito=Nunito({
  subsets: ["latin"],
  display: "swap",
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={nunito.className}>
          <NextTopLoader showSpinner={false} color="#BE75FF" />
          <ToastContainer />
          <SupportProvider>{children}</SupportProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
